export declare namespace ns1 {
    function foo1(): void;
    class className1 {
        prop11: number;
        prop22: interName1 | undefined;
    }
    interface interName1 {
    }
}
export declare namespace ns2 {
    export function foo2(): void;
    export class className2 {
        prop21: number;
        prop22: interName1 | undefined;
    }
    interface interName1 {
    }
    export {};
}