#!/usr/bin/python3
# coding: utf-8

"""
Copyright (c) 2021 Huawei Device Co., Ltd.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Description: Execute 262 test suite configuration file
"""


import os

DATA_DIR = os.path.join("test262", "data")
ESHOST_DIR = os.path.join("test262", "eshost")
HARNESS_DIR = os.path.join("test262", "harness")

BASE_OUT_DIR = os.path.join("out", "test262")

CUR_FILE_DIR = os.path.dirname(__file__)
CODE_ROOT = os.path.abspath(os.path.join(CUR_FILE_DIR, "../../.."))
ARK_DIR = f"{CODE_ROOT}/out/hi3516dv300/clang_x64/ark/ark"
ICUI_DIR = f"{CODE_ROOT}/out/hi3516dv300/clang_x64/global/i18n_standard"
LLVM_DIR = f"{CODE_ROOT}/prebuilts/clang/ohos/linux-x86_64/llvm/lib/"
ARK_JS_RUNTIME_DIR = f"{CODE_ROOT}/out/hi3516dv300/clang_x64/ark/ark_js_runtime"

# " mode_type": {
#     "1": "only default",
#     "2": "only strict mode",
#     "3": "both default and strict mode"
# }
DEFAULT_MODE = 2

TEST_ES5_DIR = os.path.join(DATA_DIR, "test_es51")
TEST_ES2015_DIR = os.path.join(DATA_DIR, "test_es2015")
TEST_CI_DIR = os.path.join(DATA_DIR, "test_CI")

DEFAULT_ARK_FRONTEND_TOOL = os.path.join(ARK_DIR, "build", "src", "index.js")
DEFAULT_ARK_TOOL = os.path.join(ARK_JS_RUNTIME_DIR, "ark_js_vm")
DEFAULT_LIBS_DIR = f"{ARK_DIR}:{ICUI_DIR}:{LLVM_DIR}:{ARK_JS_RUNTIME_DIR}"

DEFAULT_HOST_TYPE = "panda"
DEFAULT_HOST_PATH = "python3"
DEFAULT_THREADS = 8
DEFAULT_OTHER_ARGS = "--saveCompiledTests"
TEST262_RUNNER_SCRIPT = os.path.join(HARNESS_DIR, "bin", "run.js")
DEFAULT_TIMEOUT = 60000


ES5_LIST_FILE = os.path.join("test262", "es5_tests.txt")
ES2015_LIST_FILE = os.path.join("test262", "es2015_tests.txt")
CI_LIST_FILE = os.path.join("test262", "CI_tests.txt")

TEST262_GIT_HASH = "9ca13b12728b7e0089c7eb03fa2bd17f8abe297f"
HARNESS_GIT_HASH = "9c499f028eb24e67781435c0bb442e00343eb39d"
ESHOST_GIT_HASH = "fa2d4d27d9d6152002bdef36ee2d17e98b886268"
ESNEXT_GIT_HASH = "281eb10b2844929a7c0ac04527f5b42ce56509fd"

TEST262_GIT_URL = "https://gitee.com/Han00000000/test262.git"
ESHOST_GIT_URL = "https://gitee.com/Han00000000/eshost.git"
HARNESS_GIT_URL = "https://gitee.com/Han00000000/test262-harness.git"

SKIP_LIST_FILE = os.path.join("test262", "skip_tests.json")
ALL_SKIP_TESTS = []

ARK_FRONTEND_LIST = [
    "ts2panda",
    "es2panda"
]
DEFAULT_ARK_FRONTEND = ARK_FRONTEND_LIST[0]

ARK_ARCH_LIST = [
    "x64",
    "aarch64",
    "arm"
]

DEFAULT_ARK_ARCH = ARK_ARCH_LIST[0]

MODULE_FILES_LIST = [
    "early-dup-export-decl.js",
    "early-dup-export-dflt-id.js",
    "early-dup-export-dflt.js",
    "early-dup-export-id-as.js",
    "early-dup-export-id.js",
    "early-dup-lables.js",
    "early-dup-lex.js",
    "early-export-global.js",
    "early-lex-and-var.js",
    "early-new-target.js",
    "early-strict-mode.js",
    "early-super.js",
    "early-undef-break.js",
    "early-undef-continue.js",
    "parse-err-export-dflt-const.js",
    "parse-err-export-dflt-let.js",
    "parse-err-export-dflt-var.js",
    "parse-err-return.js",
    "parse-err-yield.js",
    "dup-bound-names.js",
    "await-module.js",
    "comment-multi-line-html-close.js",
    "comment-single-line-html-close.js",
    "comment-single-line-html-open.js",
    "early-dup-export-as-star-as.js",
    "early-dup-export-decl.js",
    "early-dup-export-dflt-id.js",
    "early-dup-export-dflt.js",
    "early-dup-export-id-as.js",
    "early-dup-export-id.js",
    "export-star-as-dflt.js",
    "early-dup-lables.js",
    "early-dup-lex.js",
    "early-export-global.js",
    "early-export-ill-formed-string.js",
    "early-export-unresolvable.js",
    "early-import-arguments.js",
    "early-import-as-arguments.js",
    "early-import-as-eval.js",
    "early-import-eval.js",
    "early-lex-and-var.js",
    "early-new-target.js",
    "early-strict-mode.js",
    "early-super.js",
    "early-undef-break.js",
    "early-undef-continue.js",
    "eval-export-cls-semi.js",
    "eval-export-dflt-cls-anon.js",
    "eval-export-dflt-cls-anon-semi.js",
    "eval-export-dflt-cls-named.js",
    "eval-export-dflt-cls-named-semi.js",
    "eval-export-dflt-cls-name-meth.js",
    "eval-export-dflt-expr-cls-anon.js",
    "eval-export-dflt-expr-cls-named.js",
    "eval-export-dflt-expr-cls-name-meth.js",
    "eval-export-dflt-expr-err-eval.js",
    "eval-export-dflt-expr-err-get-value.js",
    "eval-export-dflt-expr-fn-anon.js",
    "eval-export-dflt-expr-fn-named.js",
    "eval-export-dflt-expr-gen-anon.js",
    "eval-export-dflt-expr-gen-named.js",
    "eval-export-dflt-expr-in.js",
    "eval-export-dflt-fun-anon-semi.js",
    "eval-export-dflt-fun-named-semi.js",
    "eval-export-dflt-gen-anon-semi.js",
    "eval-export-dflt-gen-named-semi.js",
    "eval-export-fun-semi.js",
    "eval-export-gen-semi.js",
    "eval-gtbndng-indirect-trlng-comma_FIXTURE.js",
    "eval-gtbndng-indirect-trlng-comma.js",
    "eval-gtbndng-indirect-update-as_FIXTURE.js",
    "eval-gtbndng-indirect-update-as.js",
    "eval-gtbndng-indirect-update-dflt_FIXTURE.js",
    "eval-gtbndng-indirect-update-dflt.js",
    "eval-gtbndng-indirect-update_FIXTURE.js",
    "eval-gtbndng-indirect-update.js",
    "eval-gtbndng-local-bndng-cls.js",
    "eval-gtbndng-local-bndng-const.js",
    "eval-gtbndng-local-bndng-let.js",
    "eval-gtbndng-local-bndng-var.js",
    "eval-rqstd-abrupt-err-type_FIXTURE.js",
    "eval-rqstd-abrupt-err-uri_FIXTURE.js",
    "eval-rqstd-abrupt.js",
    "eval-rqstd-once_FIXTURE.js",
    "eval-rqstd-once.js",
    "eval-rqstd-order-1_FIXTURE.js",
    "eval-rqstd-order-2_FIXTURE.js",
    "eval-rqstd-order-3_FIXTURE.js",
    "eval-rqstd-order-4_FIXTURE.js",
    "eval-rqstd-order-5_FIXTURE.js",
    "eval-rqstd-order-6_FIXTURE.js",
    "eval-rqstd-order-7_FIXTURE.js",
    "eval-rqstd-order-8_FIXTURE.js",
    "eval-rqstd-order-9_FIXTURE.js",
    "eval-rqstd-order.js",
    "eval-self-abrupt.js",
    "eval-self-once.js",
    "eval-this.js",
    "export-default-asyncfunction-declaration-binding-exists.js",
    "export-default-asyncfunction-declaration-binding.js",
    "export-default-asyncgenerator-declaration-binding-exists.js",
    "export-default-asyncgenerator-declaration-binding.js",
    "export-default-function-declaration-binding-exists.js",
    "export-default-function-declaration-binding.js",
    "export-default-generator-declaration-binding-exists.js",
    "export-default-generator-declaration-binding.js",
    "export-expname-binding-string.js",
    "export-expname_FIXTURE.js",
    "export-expname-from-as-unpaired-surrogate.js",
    "export-expname-from-binding-string.js",
    "export-expname-from-star.js",
    "export-expname-from-star-string.js",
    "export-expname-from-star-unpaired-surrogate.js",
    "export-expname-from-string-binding.js",
    "export-expname-from-string.js",
    "export-expname-from-string-string.js",
    "export-expname-from-unpaired-surrogate.js",
    "export-expname-import-string-binding.js",
    "export-expname-import-unpaired-surrogate.js",
    "export-expname-string-binding.js",
    "export-expname-unpaired-surrogate.js",
    "export-star-as-dflt_FIXTURE.js",
    "export-star-as-dflt.js",
    "instn-iee-bndng-cls_FIXTURE.js",
    "instn-iee-bndng-cls.js",
    "instn-iee-bndng-const_FIXTURE.js",
    "instn-iee-bndng-const.js",
    "instn-iee-bndng-fun_FIXTURE.js",
    "instn-iee-bndng-fun.js",
    "instn-iee-bndng-gen_FIXTURE.js",
    "instn-iee-bndng-gen.js",
    "instn-iee-bndng-let_FIXTURE.js",
    "instn-iee-bndng-let.js",
    "instn-iee-bndng-var_FIXTURE.js",
    "instn-iee-bndng-var.js",
    "instn-iee-err-ambiguous-1_FIXTURE.js",
    "instn-iee-err-ambiguous-2_FIXTURE.js",
    "instn-iee-err-ambiguous-as.js",
    "instn-iee-err-ambiguous_FIXTURE.js",
    "instn-iee-err-ambiguous.js",
    "instn-iee-err-circular-as.js",
    "instn-iee-err-circular_FIXTURE.js",
    "instn-iee-err-circular.js",
    "instn-iee-err-dflt-thru-star-as.js",
    "instn-iee-err-dflt-thru-star-dflt_FIXTURE.js",
    "instn-iee-err-dflt-thru-star-int_FIXTURE.js",
    "instn-iee-err-dflt-thru-star.js",
    "instn-iee-err-not-found-as.js",
    "instn-iee-err-not-found-empty_FIXTURE.js",
    "instn-iee-err-not-found.js",
    "instn-iee-iee-cycle-2_FIXTURE.js",
    "instn-iee-iee-cycle.js",
    "instn-iee-star-cycle-2_FIXTURE.js",
    "instn-iee-star-cycle-indirect-x_FIXTURE.js",
    "instn-iee-star-cycle.js",
    "instn-iee-trlng-comma_FIXTURE.js",
    "instn-iee-trlng-comma.js",
    "instn-local-bndng-cls.js",
    "instn-local-bndng-const.js",
    "instn-local-bndng-export-cls.js",
    "instn-local-bndng-export-const.js",
    "instn-local-bndng-export-fun.js",
    "instn-local-bndng-export-gen.js",
    "instn-local-bndng-export-let.js",
    "instn-local-bndng-export-var.js",
    "instn-local-bndng-for-dup.js",
    "instn-local-bndng-for.js",
    "instn-local-bndng-fun.js",
    "instn-local-bndng-gen.js",
    "instn-local-bndng-let.js",
    "instn-local-bndng-var-dup.js",
    "instn-local-bndng-var.js",
    "instn-named-bndng-cls.js",
    "instn-named-bndng-const.js",
    "instn-named-bndng-dflt-cls.js",
    "instn-named-bndng-dflt-expr.js",
    "instn-named-bndng-dflt-fun-anon.js",
    "instn-named-bndng-dflt-fun-named.js",
    "instn-named-bndng-dflt-gen-anon.js",
    "instn-named-bndng-dflt-gen-named.js",
    "instn-named-bndng-dflt-named.js",
    "instn-named-bndng-dflt-star.js",
    "instn-named-bndng-fun.js",
    "instn-named-bndng-gen.js",
    "instn-named-bndng-let.js",
    "instn-named-bndng-trlng-comma.js",
    "instn-named-bndng-var.js",
    "instn-named-err-ambiguous-1_FIXTURE.js",
    "instn-named-err-ambiguous-2_FIXTURE.js",
    "instn-named-err-ambiguous-as.js",
    "instn-named-err-ambiguous_FIXTURE.js",
    "instn-named-err-ambiguous.js",
    "instn-named-err-dflt-thru-star-as.js",
    "instn-named-err-dflt-thru-star-dflt_FIXTURE.js",
    "instn-named-err-dflt-thru-star-dflt.js",
    "instn-named-err-dflt-thru-star-int_FIXTURE.js",
    "instn-named-err-not-found-as.js",
    "instn-named-err-not-found-dflt.js",
    "instn-named-err-not-found-empty_FIXTURE.js",
    "instn-named-err-not-found.js",
    "instn-named-id-name.js",
    "instn-named-iee-cycle-2_FIXTURE.js",
    "instn-named-iee-cycle.js",
    "instn-named-star-cycle-2_FIXTURE.js",
    "instn-named-star-cycle-indirect-x_FIXTURE.js",
    "instn-named-star-cycle.js",
    "instn-once.js",
    "instn-resolve-empty-export_FIXTURE.js",
    "instn-resolve-empty-export.js",
    "instn-resolve-empty-import_FIXTURE.js",
    "instn-resolve-empty-import.js",
    "instn-resolve-err-syntax-1_FIXTURE.js",
    "instn-resolve-err-syntax-1.js",
    "instn-resolve-err-syntax-2_FIXTURE.js",
    "instn-resolve-err-syntax-2.js",
    "instn-resolve-order-depth-child_FIXTURE.js",
    "instn-resolve-order-depth.js",
    "instn-resolve-order-depth-reference_FIXTURE.js",
    "instn-resolve-order-depth-syntax_FIXTURE.js",
    "instn-resolve-order-src.js",
    "instn-resolve-order-src-reference_FIXTURE.js",
    "instn-resolve-order-src-syntax_FIXTURE.js",
    "instn-resolve-order-src-valid_FIXTURE.js",
    "instn-same-global.js",
    "instn-same-global-set_FIXTURE.js",
    "instn-star-ambiguous-1_FIXTURE.js",
    "instn-star-ambiguous-2_FIXTURE.js",
    "instn-star-ambiguous_FIXTURE.js",
    "instn-star-ambiguous.js",
    "instn-star-as-props-dflt-skip.js",
    "instn-star-binding.js",
    "instn-star-equality.js",
    "instn-star-equality-other_FIXTURE.js",
    "instn-star-err-not-found-empty_FIXTURE.js",
    "instn-star-err-not-found-faulty_FIXTURE.js",
    "instn-star-err-not-found.js",
    "instn-star-id-name.js",
    "instn-star-iee-cycle-2_FIXTURE.js",
    "instn-star-iee-cycle.js",
    "instn-star-props-circular-a_FIXTURE.js",
    "instn-star-props-circular-b_FIXTURE.js",
    "instn-star-props-circular.js",
    "instn-star-props-dflt-keep-indirect-def_FIXTURE.js",
    "instn-star-props-dflt-keep-indirect.js",
    "instn-star-props-dflt-keep-indirect-reexport_FIXTURE.js",
    "instn-star-props-dflt-keep-local.js",
    "instn-star-props-dflt-keep-local-named_FIXTURE.js",
    "instn-star-props-dflt-keep-local-prod_FIXTURE.js",
    "instn-star-props-dflt-skip.js",
    "instn-star-props-dflt-skip-named_FIXTURE.js",
    "instn-star-props-dflt-skip-prod_FIXTURE.js",
    "instn-star-props-dflt-skip-star-as-named-end_FIXTURE.js",
    "instn-star-props-dflt-skip-star-as-named_FIXTURE.js",
    "instn-star-props-dflt-skip-star-as-prod-end_FIXTURE.js",
    "instn-star-props-dflt-skip-star-as-prod_FIXTURE.js",
    "instn-star-props-dflt-skip-star-named_FIXTURE.js",
    "instn-star-props-dflt-skip-star-prod_FIXTURE.js",
    "instn-star-props-nrml-1_FIXTURE.js",
    "instn-star-props-nrml-indirect_FIXTURE.js",
    "instn-star-props-nrml.js",
    "instn-star-props-nrml-star_FIXTURE.js",
    "instn-star-star-cycle-2_FIXTURE.js",
    "instn-star-star-cycle-indirect-x_FIXTURE.js",
    "instn-star-star-cycle.js",
    "instn-uniq-env-rec.js",
    "instn-uniq-env-rec-other_FIXTURE.js",
    "invalid-private-names-call-expression-bad-reference.js",
    "invalid-private-names-call-expression-this.js",
    "invalid-private-names-member-expression-bad-reference.js",
    "invalid-private-names-member-expression-this.js",
    "parse-err-decl-pos-export-arrow-function.js",
    "parse-err-decl-pos-export-block-stmt.js",
    "parse-err-decl-pos-export-block-stmt-list.js",
    "parse-err-decl-pos-export-class-decl-meth.js",
    "parse-err-decl-pos-export-class-decl-method-gen.js",
    "parse-err-decl-pos-export-class-decl-method-gen-static.js",
    "parse-err-decl-pos-export-class-decl-meth-static.js",
    "parse-err-decl-pos-export-class-expr-meth-gen.js",
    "parse-err-decl-pos-export-class-expr-meth-gen-static.js",
    "parse-err-decl-pos-export-class-expr-meth.js",
    "parse-err-decl-pos-export-class-expr-meth-static.js",
    "parse-err-decl-pos-export-do-while.js",
    "parse-err-decl-pos-export-for-const.js",
    "parse-err-decl-pos-export-for-in-const.js",
    "parse-err-decl-pos-export-for-in-let.js",
    "parse-err-decl-pos-export-for-in-lhs.js",
    "parse-err-decl-pos-export-for-in-var.js",
    "parse-err-decl-pos-export-for-let.js",
    "parse-err-decl-pos-export-for-lhs.js",
    "parse-err-decl-pos-export-for-of-const.js",
    "parse-err-decl-pos-export-for-of-let.js",
    "parse-err-decl-pos-export-for-of-lhs.js",
    "parse-err-decl-pos-export-for-of-var.js",
    "parse-err-decl-pos-export-for-var.js",
    "parse-err-decl-pos-export-function-decl.js",
    "parse-err-decl-pos-export-function-expr.js",
    "parse-err-decl-pos-export-generator-decl.js",
    "parse-err-decl-pos-export-generator-expr.js",
    "parse-err-decl-pos-export-if-else.js",
    "parse-err-decl-pos-export-if-if.js",
    "parse-err-decl-pos-export-labeled.js",
    "parse-err-decl-pos-export-object-gen-method.js",
    "parse-err-decl-pos-export-object-getter.js",
    "parse-err-decl-pos-export-object-method.js",
    "parse-err-decl-pos-export-object-setter.js",
    "parse-err-decl-pos-export-switch-case-dflt.js",
    "parse-err-decl-pos-export-switch-case.js",
    "parse-err-decl-pos-export-switch-dftl.js",
    "parse-err-decl-pos-export-try-catch-finally.js",
    "parse-err-decl-pos-export-try-catch.js",
    "parse-err-decl-pos-export-try-finally.js",
    "parse-err-decl-pos-export-try-try.js",
    "parse-err-decl-pos-export-while.js",
    "parse-err-decl-pos-import-arrow-function.js",
    "parse-err-decl-pos-import-block-stmt.js",
    "parse-err-decl-pos-import-block-stmt-list.js",
    "parse-err-decl-pos-import-class-decl-meth.js",
    "parse-err-decl-pos-import-class-decl-method-gen.js",
    "parse-err-decl-pos-import-class-decl-method-gen-static.js",
    "parse-err-decl-pos-import-class-decl-meth-static.js",
    "parse-err-decl-pos-import-class-expr-meth-gen.js",
    "parse-err-decl-pos-import-class-expr-meth-gen-static.js",
    "parse-err-decl-pos-import-class-expr-meth.js",
    "parse-err-decl-pos-import-class-expr-meth-static.js",
    "parse-err-decl-pos-import-do-while.js",
    "parse-err-decl-pos-import-for-const.js",
    "parse-err-decl-pos-import-for-in-const.js",
    "parse-err-decl-pos-import-for-in-let.js",
    "parse-err-decl-pos-import-for-in-lhs.js",
    "parse-err-decl-pos-import-for-in-var.js",
    "parse-err-decl-pos-import-for-let.js",
    "parse-err-decl-pos-import-for-lhs.js",
    "parse-err-decl-pos-import-for-of-const.js",
    "parse-err-decl-pos-import-for-of-let.js",
    "parse-err-decl-pos-import-for-of-lhs.js",
    "parse-err-decl-pos-import-for-of-var.js",
    "parse-err-decl-pos-import-for-var.js",
    "parse-err-decl-pos-import-function-decl.js",
    "parse-err-decl-pos-import-function-expr.js",
    "parse-err-decl-pos-import-generator-decl.js",
    "parse-err-decl-pos-import-generator-expr.js",
    "parse-err-decl-pos-import-if-else.js",
    "parse-err-decl-pos-import-if-if.js",
    "parse-err-decl-pos-import-labeled.js",
    "parse-err-decl-pos-import-object-gen-method.js",
    "parse-err-decl-pos-import-object-getter.js",
    "parse-err-decl-pos-import-object-method.js",
    "parse-err-decl-pos-import-object-setter.js",
    "parse-err-decl-pos-import-switch-case-dflt.js",
    "parse-err-decl-pos-import-switch-case.js",
    "parse-err-decl-pos-import-switch-dftl.js",
    "parse-err-decl-pos-import-try-catch-finally.js",
    "parse-err-decl-pos-import-try-catch.js",
    "parse-err-decl-pos-import-try-finally.js",
    "parse-err-decl-pos-import-try-try.js",
    "parse-err-decl-pos-import-while.js",
    "parse-err-export-dflt-const.js",
    "parse-err-export-dflt-expr.js",
    "parse-err-export-dflt-let.js",
    "parse-err-export-dflt-var.js",
    "parse-err-hoist-lex-fun.js",
    "parse-err-hoist-lex-gen.js",
    "parse-err-invoke-anon-fun-decl.js",
    "parse-err-invoke-anon-gen-decl.js",
    "parse-err-return.js",
    "parse-err-semi-dflt-expr.js",
    "parse-err-semi-export-star.js",
    "parse-err-semi-named-export-from.js",
    "parse-err-semi-named-export.js",
    "parse-err-semi-name-space-export.js",
    "parse-err-syntax-1.js",
    "parse-err-syntax-2.js",
    "parse-err-yield.js",
    "parse-export-empty.js",
    "private-identifiers-not-empty.js",
    "privatename-not-valid-earlyerr-module-1.js",
    "privatename-not-valid-earlyerr-module-2.js",
    "privatename-not-valid-earlyerr-module-3.js",
    "privatename-not-valid-earlyerr-module-4.js",
    "privatename-not-valid-earlyerr-module-5.js",
    "privatename-not-valid-earlyerr-module-6.js",
    "privatename-not-valid-earlyerr-module-7.js",
    "privatename-not-valid-earlyerr-module-8.js",
    "privatename-valid-no-earlyerr.js",
    "verify-dfs-a_FIXTURE.js",
    "verify-dfs-b_FIXTURE.js",
    "verify-dfs.js",
    "Symbol.iterator.js",
    "Symbol.toStringTag.js",
    "define-own-property.js",
    "delete-exported-init.js",
    "delete-exported-uninit.js",
    "delete-non-exported.js",
    "enumerate-binding-uninit.js",
    "get-nested-namespace-dflt-skip.js",
    "get-nested-namespace-dflt-skip-named-end_FIXTURE.js",
    "get-nested-namespace-dflt-skip-named_FIXTURE.js",
    "get-nested-namespace-dflt-skip-prod-end_FIXTURE.js",
    "get-nested-namespace-dflt-skip-prod_FIXTURE.js",
    "get-nested-namespace-props-nrml-1_FIXTURE.js",
    "get-nested-namespace-props-nrml-2_FIXTURE.js",
    "get-nested-namespace-props-nrml-3_FIXTURE.js",
    "get-nested-namespace-props-nrml.js",
    "get-own-property-str-found-init.js",
    "get-own-property-str-found-uninit.js",
    "get-own-property-str-not-found.js",
    "get-own-property-sym.js",
    "get-prototype-of.js",
    "get-str-found-init.js",
    "get-str-found-uninit.js",
    "get-str-initialize.js",
    "get-str-not-found.js",
    "get-str-update.js",
    "get-sym-found.js",
    "get-sym-not-found.js",
    "has-property-str-found-init.js",
    "has-property-str-found-uninit.js",
    "has-property-str-not-found.js",
    "has-property-sym-found.js",
    "has-property-sym-not-found.js",
    "is-extensible.js",
    "object-hasOwnProperty-binding-uninit.js",
    "object-keys-binding-uninit.js",
    "object-propertyIsEnumerable-binding-uninit.js",
    "own-property-keys-binding-types_FIXTURE.js",
    "own-property-keys-binding-types.js",
    "own-property-keys-sort.js",
    "prevent-extensions.js",
    "set.js",
    "set-prototype-of.js",
    "set-prototype-of-null.js"
]
