/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import assert from 'assert';
import lazy { i } from './export_api';
import lazy { i as e2 } from './export_api';
import lazy { default as h1 } from './export_api';
import lazy { j, k, } from './export_api';
import lazy { j as f2, k as g2, } from './export_api';
import lazy { type u } from './export_type';
import lazy { type v as h2 } from './export_type';
import lazy { type default as n1 } from './export_type';
import lazy { as, type a1 } from './export_type';
import lazy { b1, type e1 as i2 } from './export_type';
import j2 from './export_api';
import { k2 } from './export_api';
import "";
import '';
import './export_api';
